### ISSUE TITLE
HTTP error

### ISSUE THREAD

**Issue by jonyen** [nickb1080/nba#21] opened 2016-02-04 04:08 UTC
I've been starting to see these errors when making a Scoreboard API call:

`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://stats.nba.com/stats/scoreboard/?LeagueID=00&GameDate=02%2F01%2F2016&DayOffset=0`

I can add an exception for this, but I don't know why these calls stopped working. When I actually go to the URL, it works just fine. Kind of annoying.

**Comment by ppop** [comment] 2016-02-22 00:02
Not sure if you're not aware of this by now - NBA changed their API policy so you would need to provide HTTP headers with the request in order for this to work. 

You will always be able to hit the endpoint from your browser on the other hand.

**Comment by jonyen** [comment] 2016-02-23 19:10
Could you show me an example of how to provide the HTTP header in the request?

**Comment by danielwelch** [comment] 2016-02-24 14:31
This may or may not be related, so my apologies if this is off-topic, but it looks like the `stats.nba.com/stats/scoreboard` endpoint was recently changed. There's some discussion of it on [this reddit thread](https://www.reddit.com/r/nba/comments/3k91g5/finally_some_documentation_for_the_statsnbacom_api/czw0rql), and it appears the problem is specific to the scoreboard endpoint, or at least doesn't affect every endpoint.

When making calls to the Scoreboard endpoint, I started receiving the following 403 Forbidden error: `Referral Denied: You don't have permission to access "http://stats.nba.com/stats/scoreboard/?" on this server. Reference #24.1647f8a2.1456323795.220ea02f`. Same thing when trying in the browser.

It looks like you can get around this by setting the Referer header to `http://stats.nba.com/scores/`.

**Comment by nickb1080** [comment] 2016-02-25 04:39
Hi folks, sorry for the delay. This should be resolved in v2.0. However, it seems NBA has removed two endpoints (`playerDashPtShotLog` and `playerDashPtReboundLogs`), so those are removed and therefore it's a semver major version bump.

I used the headers from https://github.com/seemethere/nba_py/blob/79b764ec86a4740b0460ab8c75483f41247e940f/nba_py/__init__.py#L14

**Closed** 2016-02-25 04:41 UTC
