### ISSUE TITLE
Test responses are undefined

### ISSUE THREAD

**Issue by jasonLaster** [nickb1080/nba#16] opened 2015-11-11 16:10 UTC
Tried testing out the lib and found that responses are undefined.

Is this expected?

```patch
diff --git a/test/integration/stats.js b/test/integration/stats.js
index 93eb1fa..6115fbc 100644
--- a/test/integration/stats.js
+++ b/test/integration/stats.js
@@ -16,6 +16,7 @@ describe("#playerProfile", function () {
   it("works", function (done) {
     stats.playerProfile({playerId: steph}, function (err, response) {
       global.StatsData.playerProfile = response;
+      console.log('> profile', response);
       done(err);
     });
   });
@@ -25,6 +26,7 @@ describe("#playerInfo", function () {
   it("works", function (done) {
     stats.playerInfo({playerId: steph}, function (err, response) {
       global.StatsData.playerInfo = response;
+      console.log('> info', response);
       done(err);
     });
   });
@@ -34,6 +36,8 @@ describe("#playersInfo", function () {
   it("works", function (done) {
     stats.playersInfo(function (err, response) {
       global.StatsData.playersInfo = response;
+      console.log('> info', response);
+
       done(err);
     });
   });
```

```
> profile undefined
> info undefined
> info undefined
```

**Comment by nickb1080** [comment] 2015-11-16 21:39
Hmm! Thanks for pointing that out. I couldn't reproduce this with the latest commit at the time you posted this. When adding the first line `console.log('> profile', response);` I get the following result https://gist.github.com/nickb1080/9721f63b86051e942cf4

Are you still seeing this issue?

**Comment by jasonLaster** [comment] 2015-11-19 17:13
will look. Thanks

**Comment by nickb1080** [comment] 2015-11-21 01:15
Let me know if the issue persists, otherwise I'll close this in another day or so.

**Closed** 2015-12-02 06:11 UTC
